### ISSUE TITLE
`UnityEngine.Networking.NetworkTransport' does not contain a definition for `LoadEncryptionLibrary'

### ISSUE THREAD

**Issue by BageN** [Unity-Technologies/UnetEncryptionExample#4]
I downloaded the example, opened it in unity 2017.4.1f1 and I get this error:
Assets / PluginInit.cs (108.59): error CS0117: `UnityEngine.Networking.NetworkTransport 'does not contain a definition for` LoadEncryptionLibrary'
I began to look for this medod in the documentation, but I can not find it there either, only UnloadEncryptionLibrary (https://docs.unity3d.com/ScriptReference/Networking.NetworkTransport.UnloadEncryptionLibrary.html). What am I doing wrong? Thanks!

**Comment by peter-pimley-unity** [comment]
Hi @BageN, thanks for reporting this.

Apologies for the delayed response, I've been away.

The documentation does not make it clear that this is supported only in versions 2018.4 (from 2018.4.16) and 2019.3 (from 2019.3.0a6).  I will adjust the README.md to make this clear.

Thanks,
Peter

**Comment by BageN** [comment]
Hi @peter-pimley-unity !
The example itself is saved in UNITY 2017.4. Can Likak use it in the UNITY 2017.4 version?

**Comment by peter-pimley-unity** [comment]
That's a valid observation.

Our very early work on this feature was done on a custom version of 2017.4 for an enterprise support customer.  We then went back and implemented it for general use, working in the latest version at the time which was 2019.3.  We then backported it to 2018.4.

We will not backport this to 2017.4.  We made this decision after considering the following:

- 2017.4 reaches end-of-support at the end of this month.  You should really be making arrangements to move to 2018.4 or later, especially if you are on a console platform.
- We could introduce new bugs (LTS releases are supposed not to get new features).
- Other work to be carried out by the same team.
